[package]
name = "sql_reveser_error"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exitfailure = "0.5.1"
mysql = "22.1.0"
quicli = "0.4.0"
serde_yaml = "0.8.23"
tera = "1.15.0"
